import type { Shift } from "./types";

// SAMPLE DATA ONLY. Replace this array with Supabase rows when kitchens are onboarded.
// Keeping the UI dependent on the Shift type makes that swap small and predictable.
export const SAMPLE_SHIFTS: readonly Shift[] = [
  {
    id: "sample-hc-sat-breakfast",
    kitchen: "Sample Community Kitchen",
    address: "748 Mercy Street, Mountain View",
    date: "2026-10-03",
    dateLabel: "Sat, Oct 3",
    time: "7:30–11:30 AM",
    startTime: "7:30 AM",
    endTime: "11:30 AM",
    hours: 4,
    role: "Breakfast service",
    spotsLeft: 3,
    languages: ["English", "Spanish"],
    transit: "5 min from bus 22",
    transitMinutes: 5,
    accessibility: "Standing role; seated tasks available",
    description: "Set up tables, serve breakfast, and help clean the dining room.",
    supervisor: "Sample supervisor",
    organizationPhone: "(650) 555-0142",
    coordinates: [37.405, -122.08],
  },
  {
    id: "sample-pantry-tue",
    kitchen: "Sample Neighborhood Pantry",
    address: "210 Castro Street, Mountain View",
    date: "2026-10-06",
    dateLabel: "Tue, Oct 6",
    time: "1:00–5:00 PM",
    startTime: "1:00 PM",
    endTime: "5:00 PM",
    hours: 4,
    role: "Grocery packing",
    spotsLeft: 6,
    languages: ["English", "Mandarin"],
    transit: "2 min from Mountain View Transit Center",
    transitMinutes: 2,
    accessibility: "Seated and standing roles available",
    description: "Pack produce and pantry staples for afternoon pickup.",
    supervisor: "Sample supervisor",
    organizationPhone: "(650) 555-0168",
    coordinates: [37.394, -122.076],
  },
  {
    id: "sample-dining-sun",
    kitchen: "Sample Family Dining Room",
    address: "95 Hope Avenue, San Jose",
    date: "2026-10-11",
    dateLabel: "Sun, Oct 11",
    time: "3:30–7:30 PM",
    startTime: "3:30 PM",
    endTime: "7:30 PM",
    hours: 4,
    role: "Dinner prep",
    spotsLeft: 2,
    languages: ["English", "Spanish"],
    transit: "8 min from light rail",
    transitMinutes: 8,
    accessibility: "Standing role",
    description: "Prepare ingredients, plate meals, and reset the kitchen after service.",
    supervisor: "Sample supervisor",
    organizationPhone: "(408) 555-0189",
    coordinates: [37.365, -121.914],
  },
];

export const SHIFT_DATA_NOTICE =
  "These shifts are sample data. No kitchen is represented as a current ShiftCred partner.";
